### PR TITLE
feat(landing): HNDJB-8 add princh to team members

### PR DESCRIPTION
**Pull request by princhcanal**
## Description
- adds princh to team members

## Checklist

_First, create a draft pull request. Then delete any item in the checklist that doesn't apply to the PR. Then mark the PR as ready for review when all the necessary checkboxes are checked_

- [x] Reviewed own code
- [x] All GitHub status checks pass
- [x] The frontend and backend PR previews have been deployed

### CODE REVIEW

**Review by geneTickss — DISMISSED** [review]

**Review by beefysalad — COMMENTED** [review]
nice

**Review by beefysalad — DISMISSED** [review]
nice

**Comment by beefysalad** [comment]
akong pangandoy sa kinabuhi kay mahimong princhg0d

**Review by geneTickss — CHANGES_REQUESTED** [review]
Bitiag nawng ani uy

**Review by beefysalad — APPROVED** [review]
Mas ni gwapo og samot!

**Review by geneTickss — APPROVED** [review]
Good job

**Pull request merged**
